name: Build » Test build

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

env:
  NODE_VERSION: 24

jobs:
  check-npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Ensure our node version matches the main repo's version
        if: github.event_name == 'pull_request'
        run: |
          [[ "$(curl -s https://raw.githubusercontent.com/opencast/opencast/refs/heads/${{ github.base_ref }}/pom.xml | \
              grep node.version | grep -Eo 'v[0-9.]+' | cut -f 1 -d '.' | cut -c 2-)" == "$NODE_VERSION" ]] \
          && exit 0 \
          || (echo "Node version does not match"; exit 1)
      - name: Ensure our node version matches the main repo's version
        if: github.event_name == 'push'
        run: |
          [[ "$(curl -s https://raw.githubusercontent.com/opencast/opencast/refs/heads/${{ github.ref_name }}/pom.xml | \
              grep node.version | grep -Eo 'v[0-9.]+' | cut -f 1 -d '.' | cut -c 2-)" == "$NODE_VERSION" ]] \
          && exit 0 \
          || (echo "Node version does not match"; exit 1)

      - name: Get Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ NODE_VERSION }}

      - name: Run npm ci
        run: npm ci

      - name: Build the app
        run: npm run build
